### ISSUE TITLE
[Bug] `Disconnect::handle_disconnect` doesn't appear to be triggering, despite `Disconnect::enable_disconnect` working

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#2102]
## 🐛 Bug Report

This change https://github.com/AleoHQ/snarkOS/pull/2101/commits/7a7797d0d91f736e2fed04beb2435b27f853089b was added in PR #2101 because of a bug whereby the disconnect handler from the `tcp` stack does not appear to be triggering `snarkos_tcp::protocols::Disconnect::handle_disconnect`.

The way I triggered this was by having more than the minimum number of peers, so that triggers the refresh peers logic, and thus the disconnect failure.

Here is a screenshot of the bug in action:

![Screen Shot 2022-11-27 at 9 15 56 PM](https://user-images.githubusercontent.com/9260812/204199619-f6fbb3de-4f52-4f5c-91ed-6f69b4b78907.png)

At `04:49:02`, the first call to disconnect is made. It appears the peer may be disconnected in the `Tcp` stack. However, during the disconnect, `handle_disconnect` doesn't appear to be triggered, since calling `handle_disconnect` will invoke `router.remove_connected_peer(peer_ip)`, which clears the peer from the `Router`.

As a result, the peer remains connected (and becomes what we call a "stale" peer) on the `Router` level (but is already removed on the `Tcp` level), as shown in the following screenshot:

![Screen Shot 2022-11-27 at 9 16 13 PM](https://user-images.githubusercontent.com/9260812/204199869-5dc514a6-abe7-4392-9011-66c9a8549318.png)

## Steps to Reproduce

Try running the penultimate commit https://github.com/AleoHQ/snarkOS/pull/2101/commits/cc7db5c7bb1e7237e26ddc6a325a3e0774dd6baa for **at least 30 minutes** with the following command:
```
cargo run --release -- start --nodisplay --prover "APrivateKey1zkpAECeZYpLE5vcwcRdsb8NpRqEe182C4NApb12BonN1fyS" --verbosity 1
```

#### Alternative

If the "production mode" approach doesn't work, I have not tried this, but I would suggest to try running at least 4 dev nodes. I suspect it would also reproduce the issue.

The idea is that you need to have more than the minimum number of peers, then trigger the refresh peers logic, and see the disconnect failure.

Terminal 1:
```
cargo run --release -- start --nodisplay --dev 0 --beacon ""
```
Terminal 2:
```
cargo run --release -- start --nodisplay --dev 1 --validator ""
```
Terminal 3:
```
cargo run --release -- start --nodisplay --dev 2 --validator ""
```
Terminal 4:
```
cargo run --release -- start --nodisplay --dev 3 --prover "" --verbosity 1
```

Similarly, run for at least 30 minutes, and watch the prover (i.e. the 4th terminal window).

## Your Environment

- Run snarkOS @ https://github.com/AleoHQ/snarkOS/pull/2101/commits/cc7db5c7bb1e7237e26ddc6a325a3e0774dd6baa
- Ubuntu 22.04
- Aleo Testnet 3, Phase 2, Production

**Comment by xbeastx** [comment]
don't know if it's releated but got assert sometimes:
```
2022-11-30T21:24:04.513395Z DEBUG Connected to 9 peers [46.101.114.158:4133, 49.51.90.113:4133, 43.157.46.41:4133, 43.157.40.51:4133, 43.157.46.192:4133, 192.248.152.240:4133, 43.155.175.209:4133, 43.131.250.33:4133, 43.156.122.66:4133]
2022-11-30T21:24:04.513479Z  INFO Disconnecting from '49.51.90.113:4133' (periodic refresh of peers)
thread 'tokio-runtime-worker' panicked at 'assertion failed: _disconnected', .../snarkOS/node/router/src/lib.rs:150
2022-11-30T21:24:04.515423Z DEBUG Connecting to 125.132.1.74:4133...
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by niklaslong** [comment]
@xbeastx This is a debug assert (won't be compiled into the binary if you build with `--release`). This is expected to trigger with our current disconnect logic (which will be further improved soon).

**Comment by howardwu** [comment]
On the latest commit, I tried removing my bandaid (of double disconnecting) and can confirm the `connected` list of peers in the router and Tcp stack do not match. Adding the bandaid back fixes the problem on the latest commit, so the issue is still there.

**Comment by ljedrz** [comment]
This should be fixed by https://github.com/AleoHQ/snarkOS/pull/2168.

**Comment by damomine** [comment]
This problem is still exist
tokio-runtime-worker' panicked at 'assertion failed: _disconnected',

and  the incoming connections can't be remove
by checking  
netstat -aptn | grep snarkos
and 
curl 127.0.0.1:3033/testnet3/peers/all

**Comment by ljedrz** [comment]
@damomine I assume you're not running `--release` for debugging purposes?

As for the issue persisting, I'm pretty sure it's some call to `Router::disconnect` that doesn't resolve the address at the callsite; I've been working on using strong typing to prevent them from being mixed up, but it's blocked by the other pending changes.

**Comment by damomine** [comment]
> @damomine I assume you're not running `--release` for debugging purposes?
> 
> As for the issue persisting, I'm pretty sure it's some call to `Router::disconnect` that doesn't resolve the address at the callsite; I've been working on using strong typing to prevent them from being mixed up, but it's blocked by the other pending changes.

yes, we test snarkos on debugging mode,  
thanks for your reply and solutions!

**Comment by ljedrz** [comment]
Thank _you_ for the aid in debugging! If you'd like to test a further fix, please feel free to apply [this commit](https://github.com/AleoHQ/snarkOS/pull/2181/commits/6fc649312793ed20caac55831bd634131a226195), which should hopefully resolve all the remaining cases of this issue. Also, you can still run the node in the much faster `--release` mode and test it, by changing [this line](https://github.com/AleoHQ/snarkOS/blob/8f7f6d99d96e6dda3d825885d35017d0633da368/node/router/src/lib.rs#L147) from `debug_assert` to `assert` locally.

**Comment by ljedrz** [comment]
This should already be fixed with the aforementioned PRs.
