### ISSUE TITLE
[Bug] Client nodes often fail to synchronize through CDN

### ISSUE THREAD

**Issue by elderhammer** [AleoHQ/snarkOS#2951]
## 🐛 Bug Report

Client nodes often fail to synchronize through CDN, and can only be resynchronized after cleaning.

## Steps to Reproduce

1. Start node and sync via cdn
2. There is a chance that the following error will occur: "Failed to process block 16703: Failed to finalize transactions - Mismatch in finalize operations for an accepted execute"
3. After the above error occurs, block synchronization through CDN will no longer be possible. There are two ways to deal with this situation: the first is to continue synchronization through the p2p network (the speed is very slow), and the second is to clean the local data and then synchronize again through CDN (the same error may occur again). Either method is a waste of time.

## logs

1. Failed to process block 16703: Failed to finalize transactions - Mismatch in finalize operations for an accepted execute - (found: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"1855599170774902129656644777997628845429219544613200465883255687889211551576field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"7692377386860911629174188256135546716941218122125000790194996245802297591275field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"7349540888910680014867714311411642487787384475157899685379129835259527066348field"}], expected: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"3601746700575322993009320430561140428297596655231117442676544587352644390356field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"1853673008182840802009216333633484463125840168286044602959876381414979701986field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"6376971543460486268666713934088030615242501953235333824380014028909750813998field"}])
2. Failed to process block 991191: Failed to finalize transactions - Mismatch in finalize operations for an accepted execute - (found: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"7997339194803135996593873274892347677160504931726061110021550349243502143305field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"5711872819321488745907164894751155944876575791581787155312415298250182532433field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"617674574432878097022785481636383699528492813671554655476179720374583299539field"}], expected: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"81467806830472327220723979803228347059210147584240172230333237689505372754field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"2335606834670260709568178915040882011748123703057278086292720977889517153245field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"3065229506875392332395767368781258661520432853255489205694165923355198001586field"}])

## Expected Behavior

1. No more that error
2. Provide some incremental processing methods, such as rolling back partial height blocks from the ledger

## Your Environment

- snarkOS Version: 8d75c10802003d2c7f4c29fc2e49b4a703b7a530
- Rust Version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
- Computer OS: Ubuntu 20.04.6 LTS

**Comment by howardwu** [comment]
Can you try starting a clean snarkOS client built from this PR to confirm this issue is fixed?
https://github.com/AleoHQ/snarkOS/pull/2914

**Comment by elderhammer** [comment]
> Can you try starting a clean snarkOS client built from this PR to confirm this issue is fixed?
> 
> https://github.com/AleoHQ/snarkOS/pull/2914

OK, I will try it.

**Comment by elderhammer** [comment]
This problem still occurs. @howardwu 
I stop and restart nodes frequently and I think this is the direct cause.
snarkOS Version: 73d765f2ff0634bc60bac3189460c17cb73c6248

### log
```
2024-01-12T09:37:37.083700Z DEBUG Loading deployments 92928-93184 (of 94181)...
2024-01-12T09:37:37.141899Z DEBUG Loading deployments 93184-93440 (of 94181)...
2024-01-12T09:37:37.210586Z DEBUG Loading deployments 93440-93696 (of 94181)...
2024-01-12T09:37:37.298148Z DEBUG Loading deployments 93696-93952 (of 94181)...
2024-01-12T09:37:37.361558Z DEBUG Loading deployments 93952-94181 (of 94181)...
2024-01-12T09:37:42.036268Z DEBUG Requesting blocks 1163050 to 1163100 (of 1163800)
2024-01-12T09:37:42.036305Z DEBUG Requesting blocks 1163100 to 1163150 (of 1163800)
2024-01-12T09:37:42.036310Z DEBUG Requesting blocks 1163150 to 1163200 (of 1163800)
2024-01-12T09:37:42.036313Z DEBUG Requesting blocks 1163200 to 1163250 (of 1163800)
2024-01-12T09:37:42.036317Z DEBUG Requesting blocks 1163250 to 1163300 (of 1163800)
2024-01-12T09:37:42.036321Z DEBUG Requesting blocks 1163300 to 1163350 (of 1163800)
2024-01-12T09:37:42.036325Z DEBUG Requesting blocks 1163350 to 1163400 (of 1163800)
2024-01-12T09:37:42.036329Z DEBUG Requesting blocks 1163400 to 1163450 (of 1163800)
2024-01-12T09:37:42.036334Z DEBUG Requesting blocks 1163450 to 1163500 (of 1163800)
2024-01-12T09:37:42.036338Z DEBUG Requesting blocks 1163500 to 1163550 (of 1163800)
2024-01-12T09:37:42.036343Z DEBUG Requesting blocks 1163550 to 1163600 (of 1163800)
2024-01-12T09:37:42.036347Z DEBUG Requesting blocks 1163600 to 1163650 (of 1163800)
2024-01-12T09:37:42.036351Z DEBUG Requesting blocks 1163650 to 1163700 (of 1163800)
2024-01-12T09:37:42.036356Z DEBUG Requesting blocks 1163700 to 1163750 (of 1163800)
2024-01-12T09:37:42.036360Z DEBUG Requesting blocks 1163750 to 1163800 (of 1163800)
2024-01-12T09:38:06.117054Z WARN Failed to process block 1163054: Failed to finalize transactions - Mismatch in finalize operations for an accepted execute - (found: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"5789213003245192311829041372534606591752152643199632331346198598416416525231field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"6359461496572668795791781495776915814644561490253869831298365537487819216956field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"93594066306224647019852757429144496637237563744076111261838902129631143458field"}], expected: [{"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"5751135558267294610343586853779360975951068186641375618546174603191347156099field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"6045810861730487498620222696404384050219982852263960751069945993223914428075field"}, {"type":"update_key_value","mapping_id":"2855157744830843716005407030207142101853521493742120919939436395872133863104field","index":0,"key_id":"3024437819920267001397955368796529189477001337864961277902746027317009395679field","value_id":"2656277556394383388018867325112266544001294322556059316462026864255275734069field"}])
2024-01-12T09:38:07.378471Z DEBUG REST rate limit per IP - 1000 RPS
2024-01-12T09:38:07.385944Z DEBUG No connected peers
2024-01-12T09:38:07.385982Z DEBUG No connected validators
2024-01-12T09:38:07.385990Z DEBUG No connected bootstrap peer
2024-01-12T09:38:07.386065Z INFO Connected bootstrap peers: []
2024-01-12T09:38:07.386074Z INFO Connecting bootstrap peers: []
```
```
2024-01-12T09:41:48.407839Z ERROR Failed to add block request, as block 1163100 exists in the requests map
2024-01-12T09:41:48.407875Z ERROR Failed to add block request, as block 1163101 exists in the requests map
2024-01-12T09:41:48.407915Z ERROR Failed to add block request, as block 1163102 exists in the requests map
2024-01-12T09:41:48.407954Z ERROR Failed to add block request, as block 1163103 exists in the requests map
2024-01-12T09:41:48.473215Z WARN The next block (1163054) is invalid - Failed to speculate on transactions - Failed to post-ratify - Next height must be sequential
```

**Comment by elderhammer** [comment]
I started and restarted the node through the two commands: systemctl start and systemctl restart.
When systemctl restart is executed, if ExecStop=/usr/bin/kill -2 $MAINPID is not set, the SIGTERM signal will be emitted instead of the SIGINT signal.
I think this is why the block synchronization protection logic in the code does not take effect.

**Comment by ljedrz** [comment]
Since #3017 has been merged and I've successfully tested it with many restarts, I'm closing this issue; please feel free to reopen if it happens again, though.
